2024-09-09 08:58:20,269 - ERROR - ERROR - page 1 link 30 = https://money.kompas.com/read/2024/09/09/080000426/wacana-subsidi-tiket-krl-berbasis-nik-dan-ai-sudah-sampai-mana-pembahasannya-
2024-09-09 08:58:54,007 - INFO - [pid 3110] Worker Worker(salt=3076264814, workers=1, host=LAPTOP-038LGA7P, username=oscar-sinaga, pid=3110) done      ExtractScrapingData()
2024-09-09 08:58:54,008 - DEBUG - 1 running tasks, waiting for next task to finish
2024-09-09 08:58:54,011 - INFO - Informed scheduler that task   ExtractScrapingData__99914b932b   has status   DONE
2024-09-09 08:58:54,012 - DEBUG - Asking scheduler for work...
2024-09-09 08:58:54,014 - DEBUG - Pending tasks: 3
2024-09-09 08:58:54,015 - INFO - [pid 3110] Worker Worker(salt=3076264814, workers=1, host=LAPTOP-038LGA7P, username=oscar-sinaga, pid=3110) running   TransformScrapingData()
2024-09-09 08:58:54,122 - ERROR - [pid 3110] Worker Worker(salt=3076264814, workers=1, host=LAPTOP-038LGA7P, username=oscar-sinaga, pid=3110) failed    TransformScrapingData()
Traceback (most recent call last):
  File "/home/oscar-sinaga/miniconda3/lib/python3.11/site-packages/luigi/worker.py", line 210, in run
    new_deps = self._run_get_new_deps()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar-sinaga/miniconda3/lib/python3.11/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
    task_gen = self.task.run()
               ^^^^^^^^^^^^^^^
  File "/mnt/h/My Drive/pacmann/Intro to DE/ETL-pipeline/etl_luigi.py", line 123, in run
    scraping_df = transform_scraping_data(scraping_df)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/h/My Drive/pacmann/Intro to DE/ETL-pipeline/src/transformation/transform_data.py", line 202, in transform_scraping_data
    df_scraping['tanggal_waktu_publish'] = pd.to_datetime(df_scraping['tanggal_waktu_publish'], format='%d/%m/%Y, %H:%M')
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar-sinaga/miniconda3/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 1063, in to_datetime
    cache_array = _maybe_cache(arg, format, cache, convert_listlike)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar-sinaga/miniconda3/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 247, in _maybe_cache
    cache_dates = convert_listlike(unique_dates, format)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar-sinaga/miniconda3/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 433, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oscar-sinaga/miniconda3/lib/python3.11/site-packages/pandas/core/tools/datetimes.py", line 467, in _array_strptime_with_fallback
    result, tz_out = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 501, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 451, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 583, in pandas._libs.tslibs.strptime._parse_with_format
ValueError: time data "Diperbarui 09/09/2024, 08:30" doesn't match format "%d/%m/%Y, %H:%M", at position 412. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
2024-09-09 08:58:54,232 - DEBUG - 1 running tasks, waiting for next task to finish
2024-09-09 08:58:54,237 - INFO - Informed scheduler that task   TransformScrapingData__99914b932b   has status   FAILED
2024-09-09 08:58:54,238 - DEBUG - Asking scheduler for work...
2024-09-09 08:58:54,240 - DEBUG - Pending tasks: 3
2024-09-09 08:58:54,241 - INFO - [pid 3110] Worker Worker(salt=3076264814, workers=1, host=LAPTOP-038LGA7P, username=oscar-sinaga, pid=3110) running   ValidateData()
2024-09-09 08:58:57,383 - INFO - [pid 3110] Worker Worker(salt=3076264814, workers=1, host=LAPTOP-038LGA7P, username=oscar-sinaga, pid=3110) done      ValidateData()
2024-09-09 08:58:57,384 - DEBUG - 1 running tasks, waiting for next task to finish
2024-09-09 08:58:57,387 - INFO - Informed scheduler that task   ValidateData__99914b932b   has status   DONE
2024-09-09 08:58:57,387 - DEBUG - Asking scheduler for work...
2024-09-09 08:58:57,389 - DEBUG - Done
2024-09-09 08:58:57,390 - DEBUG - There are no more tasks to run at this time
2024-09-09 08:58:57,391 - DEBUG - There are 2 pending tasks possibly being run by other workers
2024-09-09 08:58:57,391 - DEBUG - There are 2 pending tasks unique to this worker
2024-09-09 08:58:57,392 - DEBUG - There are 2 pending tasks last scheduled by this worker
2024-09-09 08:58:57,393 - INFO - Worker Worker(salt=3076264814, workers=1, host=LAPTOP-038LGA7P, username=oscar-sinaga, pid=3110) was stopped. Shutting down Keep-Alive thread
2024-09-09 08:58:57,396 - INFO - 
===== Luigi Execution Summary =====

Scheduled 8 tasks of which:
* 6 ran successfully:
    - 1 ExtractMarketingData()
    - 1 ExtractSalesData()
    - 1 ExtractScrapingData()
    - 1 TransformMarketingData()
    - 1 TransformSalesData()
    ...
* 1 failed:
    - 1 TransformScrapingData()
* 1 were left pending, among these:
    * 1 had failed dependencies:
        - 1 LoadData()

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

